apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: wisecow-security-policy
  namespace: default
spec:
  selector:
    matchLabels:
      app: wisecow
  
  # Block dangerous commands
  process:
    matchPaths:
    - path: /usr/bin/wget
      action: Block
    - path: /usr/bin/curl  
      action: Block
    - path: /bin/su
      action: Block
    - path: /usr/bin/sudo
      action: Block
      
  # Protect sensitive files
  file:
    matchPaths:
    - path: /etc/passwd
      action: Block
    - path: /etc/shadow
      action: Block
      
  action: Allow  # Allow everything else by default
