apiVersion: v1
kind: Secret
metadata:
  name: wisecow-tls-secret
  namespace: wisecow
type: kubernetes.io/tls
data:
  # Base64-encoded TLS certificate and key.
  # Prefer generating this automatically using: `./scripts/deploy.sh`
  tls.crt: <base64-cert>
  tls.key: <base64-key>
